# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: point.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='point.proto',
  package='proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0bpoint.proto\x12\x05proto\"\x8b\x01\n\x0b\x44\x65vicePoint\x12\x16\n\x0e\x63olletDeviceId\x18\x01 \x01(\t\x12\x11\n\tpointName\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x0f\n\x07oemTime\x18\x05 \x01(\x03\x12\x0f\n\x07quality\x18\x06 \x01(\x05\x12\x12\n\nattributes\x18\x07 \x01(\t\"X\n\x0c\x44\x65vicePoints\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\"\n\x06points\x18\x02 \x03(\x0b\x32\x12.proto.DevicePoint\x12\x11\n\teventFlag\x18\x03 \x01(\x05\x42!\n\x16\x63om.protobuf.generatedB\x05PointP\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEVICEPOINT = _descriptor.Descriptor(
  name='DevicePoint',
  full_name='proto.DevicePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='colletDeviceId', full_name='proto.DevicePoint.colletDeviceId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pointName', full_name='proto.DevicePoint.pointName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.DevicePoint.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='proto.DevicePoint.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oemTime', full_name='proto.DevicePoint.oemTime', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quality', full_name='proto.DevicePoint.quality', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='proto.DevicePoint.attributes', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=162,
)


_DEVICEPOINTS = _descriptor.Descriptor(
  name='DevicePoints',
  full_name='proto.DevicePoints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='proto.DevicePoints.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points', full_name='proto.DevicePoints.points', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eventFlag', full_name='proto.DevicePoints.eventFlag', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=252,
)

_DEVICEPOINTS.fields_by_name['points'].message_type = _DEVICEPOINT
DESCRIPTOR.message_types_by_name['DevicePoint'] = _DEVICEPOINT
DESCRIPTOR.message_types_by_name['DevicePoints'] = _DEVICEPOINTS

DevicePoint = _reflection.GeneratedProtocolMessageType('DevicePoint', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEPOINT,
  __module__ = 'point_pb2'
  # @@protoc_insertion_point(class_scope:proto.DevicePoint)
  ))
_sym_db.RegisterMessage(DevicePoint)

DevicePoints = _reflection.GeneratedProtocolMessageType('DevicePoints', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEPOINTS,
  __module__ = 'point_pb2'
  # @@protoc_insertion_point(class_scope:proto.DevicePoints)
  ))
_sym_db.RegisterMessage(DevicePoints)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026com.protobuf.generatedB\005PointP\000'))
# @@protoc_insertion_point(module_scope)
